# Generated by Django 4.2 on 2023-04-21 02:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("Order_Id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "Product_Ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "Product_Qtys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Buyer_Name", models.CharField(max_length=100)),
                ("Buyer_Address", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("Stock_Name", models.CharField(max_length=100)),
                ("Supplier", models.CharField(max_length=100)),
                ("Product_Id", models.IntegerField(primary_key=True, serialize=False)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Quantity", models.IntegerField()),
                ("Location_Sector", models.CharField(max_length=5)),
                ("Location_Shelf", models.IntegerField()),
                ("PhotoImgName", models.CharField(max_length=100)),
            ],
        ),
    ]
