# Generated by Django 4.2 on 2023-04-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0002_orders_stock"),
    ]

    operations = [
        migrations.DeleteModel(name="Orders",),
    ]
