# Generated by Django 4.2 on 2023-04-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0004_orders"),
    ]

    operations = [
        migrations.DeleteModel(name="Stock",),
    ]
