# Generated by Django 4.2 on 2023-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0005_delete_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("Sid", models.AutoField(primary_key=True, serialize=False)),
                ("Stock_Name", models.CharField(max_length=100)),
                ("Supplier", models.CharField(max_length=100)),
                ("Product_Id", models.IntegerField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Quantity", models.IntegerField()),
                ("Location_Sector", models.CharField(max_length=5)),
                ("Location_Shelf", models.IntegerField()),
                ("PhotoImgName", models.CharField(max_length=100)),
            ],
        ),
    ]
