# Generated by Django 4.2 on 2023-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0006_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("Sector_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Sector_Name", models.CharField(max_length=100)),
                ("Sector_Capacity", models.IntegerField()),
                ("Sector_Map", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("Shelf_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Shelf_Num", models.IntegerField()),
                ("Shelf_Capacity", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Departments",),
        migrations.DeleteModel(name="Employees",),
    ]
