# Generated by Django 4.2 on 2023-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0007_sector_shelf_delete_departments_delete_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("Mid", models.AutoField(primary_key=True, serialize=False)),
                ("Map_Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="sector", name="Sector_Map",),
    ]
