# Generated by Django 4.2 on 2023-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_api", "0009_delete_shelf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("Shelf_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Shelf_Sector", models.CharField(max_length=100)),
                ("Shelf_Num", models.IntegerField()),
                ("Shelf_Capacity", models.IntegerField()),
            ],
        ),
    ]
